name: Daily Mindset Journal
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  publish-journal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install requests fpdf
    - name: Run journal automation
      env:
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        GUMROAD_TOKEN: ${{ secrets.GUMROAD_TOKEN }}
      run: |
        cat << 'EOF' > journal_automation.py
        import os
        import requests
        import datetime
        import json
        from fpdf import FPDF
        
        # API Keys from environment
        TOGETHER_KEY = os.environ.get('TOGETHER_API_KEY')
        GUMROAD_TOKEN = os.environ.get('GUMROAD_TOKEN')
        
        # Generate Journal Content
        date = datetime.datetime.now().strftime("%Y-%m-%d")
        prompt = "Create premium mindset journal for today with: 1. Powerful title 2. Motivational body 3. 5 affirmations 4. Inspirational quote 5. 3 reflection prompts 6. Gratitude section"
        
        # Debugging: Print API key status
        print(f"Using Together API key: {TOGETHER_KEY[:5]}...{TOGETHER_KEY[-5:]}")
        
        response = requests.post(
            "https://api.together.xyz/v1/chat/completions",
            headers={"Authorization": f"Bearer {TOGETHER_KEY}"},
            json={
                "model": "mistralai/Mixtral-8x7B-Instruct-v0.1",
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 1500,
                "temperature": 0.7
            }
        )
        
        # Debugging: Print full response
        print(f"API Response Status: {response.status_code}")
        print(f"API Response Body: {response.text[:200]}...")
        
        # Handle response safely
        data = response.json()
        if 'choices' not in data:
            raise Exception(f"API Error: {data.get('error', {}).get('message', 'Unknown error')}")
            
        content = data['choices'][0]['message']['content']
        
        # Create PDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=12)
        pdf.cell(200, 10, txt=f"Daily Mindset Journal - {date}", ln=True, align='C')
        pdf.ln(10)
        for line in content.split('\n'):
            pdf.multi_cell(0, 8, txt=line)
            pdf.ln(3)
        pdf.output(f"journal_{date}.pdf")
        
        # Upload to Gumroad
        with open(f"journal_{date}.pdf", "rb") as f:
            response = requests.post(
                "https://api.gumroad.com/v2/products",
                files={"file": f},
                data={
                    "name": f"Daily Mindset Journal - {date}",
                    "description": "Premium mindset journal by Unknownmous",
                    "published": "true"
                },
                auth=(GUMROAD_TOKEN, '')
            )
            print(f"Gumroad Response: {response.status_code} - {response.text}")
        EOF
        python journal_automation.py
